### ISSUE TITLE
Rename the package from teamprojekt_competition_server to comprl

### ISSUE THREAD

**Issue by Raining-Cloud** [martius-lab/teamproject-competition-server#61]
## Description
I suggest renaming the main package _teaamprojekt_competition_server_  to something simpler **like** _comprl_. While working outside our package it got really annoying typing the package name everytime. 
Also this project is initiated by the teamproject lecture but metioning this in our readme should be enough, so we could choose a simpler more effective name.

I would propose _comprl_ as a possible name, which just is the combination of competition and reinforcement learning, short but yet effective

**Comment by Raining-Cloud** [comment]
@Cari1111 @PacoSchatz @SveaGaenzle

**Comment by PacoSchatz** [comment]
I agree, great suggestion. I didn't recognize the meaning of the name at first but it's definitely better. But maybe we should discuss this change on the 06.02.

**Comment by Raining-Cloud** [comment]
> I agree, great suggestion. I didn't recognize the meaning of the name at first but it's definitely better. But maybe we should discuss this change on the 06.02.

Actually would be nice if we could decide this not in 2 weeks, but we could tag @luator and see what he thinks :)

**Comment by luator** [comment]
Hi, I'm good with renaming the package, the current name is indeed a bit awkward to work with :+1:
