### ISSUE TITLE
restructure current project layout

### ISSUE THREAD

**Issue by Raining-Cloud** [martius-lab/teamproject-competition-server#62]
# Description
Please read #61 first :)

Over time our packages got cluttered with things which shouldn't belong there. Our server and client both contain a main entry point which is currently used for some testing, I see the convience of having this but moving towards a release we should consider **removing** them. We aim to provide a package which the end use can use to build their own competition servers not to run our latest changes. 

We also offer an interface for games that use the [gymnasium](https://gymnasium.farama.org/) package, but refuse to use it ourselves. Maybe @PacoSchatz could elaborate this ? If needed we could move this into interfaces, if not delete ?

# Proposition
In addition of #61.

Create another folder **outside** our directory which contains our samples like the example game, rock paper scissors and the hockey, with corresponding agents. _We could add tests to this at this point, so that all the servers get started and n agents try joining them?_
Renaming files so they are consistent, in e.g. we have `server/protocol.py` and `client/client_protocol.py`. Maybe also moving the "netwoking" into `server/net/` or something similar?

I hacked some example structure how we could restructure:
```
comprl
|   __init__.py
|   
+---client
|   |   agent.py
|   |   __init__.py
|   |   
|   \---net
|           client.py
|           protocol.py
|           
+---server
|   |   gymgame.py
|   |   id_generator.py
|   |   interfaces.py
|   |   player.py
|   |   server.py
|   |   __init__.py
|   |   
|   +---data
|   |       game_database.py
|   |       user_database.py
|   |       
|   +---logic
|   |       game_manager.py
|   |       matchmaking.py
|   |       player_manager.py
|   |       
|   \---net
|           factory.py
|           protocol.py
|           
\---shared
|       commands.py
|       types.py
|       __init__.py
|       
(future web here ?)
```

Please leave your thoughts on this  :)

**Comment by Cari1111** [comment]
I aggree, a better layout would be very useful. The suggestet file directory makes a lot of sense. 
The only thing I would change, is having `server.py` and `client.py` either both in the `net` folder or both in the base folder.
