### ISSUE TITLE
simple user stories for the web-interface

### ISSUE THREAD

**Issue by Raining-Cloud** [martius-lab/teamproject-competition-server#66]
## Description
This issue tracks the needed features for our webinterface. This is just a complete list of what I imagine a full interface should be capable of, maybe some things are out of scope for us :)

- [ ] Login-Page

- handles login of already registered users, with a `username` and a `password`

- [ ] Register-Page

- gives the option to register a new user, needs a `username`, `password`, `master-key` and maybe an e-mail address?

- [ ] User-Dashboard

- this is the main part of the webinterface, the user should be able to see a leaderboard, search for specific games, and inspect his profile.

- [ ] Game-Inspector

- here we want to display **one** game, things like who participated, the result are important. Nice to have would be some additional statistics or an option to render the game and stream it.

- [ ] Admin-Dashboard

- this page is for the hosts of the competition. It should contain all the things the normal user can see. In addition he should be able to view and edit the registered users, and create new bot-tokens?.
- maybe we want to display some live logs here in future ?
- maybe open and close the competition server?

**Comment by SveaGaenzle** [comment]
I think this already looks very good!
I've been thinking about a few additional features that I think might be worth adding for the User-Dashboard:
- Current competitions, statistics, e.g. how many games have already been played
- Announcements to keep participants informed about updates, deadlines, and other important information.
-  It might also be nice to have a system that participants can use to report bugs etc.
